from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


_CONTRACT_VERSION = "dashboard-registry-v1"


@dataclass(frozen=True)
class DashboardRegistryEntry:
    engine_name: str
    owning_system: str
    mission: str
    dashboard: str
    section: str
    component: str
    label: str
    priority: str
    display_order: int
    visibility: str
    version_introduced: str
    evidence_requirement: str
    confidence_requirement: str
    status: str
    backward_compatibility: bool
    olympus_contract_version: str
    source: str
    value_path: str
    aggregation: str = "direct"
    default_value: Any = "Awaiting Historical Data"
    table_columns: tuple[str, ...] = ()
    delta_path: str = ""

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


def _entry(**kwargs: Any) -> DashboardRegistryEntry:
    return DashboardRegistryEntry(olympus_contract_version=_CONTRACT_VERSION, **kwargs)


_REGISTRY: tuple[DashboardRegistryEntry, ...] = (
    # Prometheus Market Analysis Dashboard
    _entry(engine_name="Execution Location Intelligence", owning_system="Prometheus", mission="Execution intelligence", dashboard="prometheus_market_analysis", section="execution", component="metric", label="Execution Location Score", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Historical execution telemetry", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_location_intelligence.execution_location_quality"),
    _entry(engine_name="Structural Price Location Intelligence", owning_system="Prometheus", mission="Execution intelligence", dashboard="prometheus_market_analysis", section="execution", component="metric", label="Structural Entry Quality", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Historical structure context", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_location_intelligence.structural_position"),
    _entry(engine_name="Execution Location Intelligence", owning_system="Prometheus", mission="Execution intelligence", dashboard="prometheus_market_analysis", section="execution", component="metric", label="Liquidity Exposure", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Liquidity exposure observations", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_location_intelligence.sweep_exposure"),
    _entry(engine_name="Capital Preservation Intelligence", owning_system="Prometheus", mission="Capital preservation", dashboard="prometheus_market_analysis", section="execution", component="metric", label="Capital Leakage", priority="High", display_order=40, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Closed loss trades", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="capital_preservation_intelligence.total_capital_leakage"),
    _entry(engine_name="Execution Intelligence", owning_system="Prometheus", mission="Execution intelligence", dashboard="prometheus_market_analysis", section="execution", component="metric", label="Execution Efficiency", priority="High", display_order=50, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Trade efficiency telemetry", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_location_intelligence.execution_efficiency"),
    _entry(engine_name="Learning Intelligence", owning_system="Prometheus", mission="Institutional learning", dashboard="prometheus_market_analysis", section="execution", component="metric", label="Intelligence Maturity", priority="Medium", display_order=60, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Historical sample size", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_learning_engine.sample_size", aggregation="maturity_from_sample"),

    _entry(engine_name="Capital Preservation Intelligence", owning_system="Prometheus", mission="Capital preservation", dashboard="prometheus_market_analysis", section="risk", component="metric", label="Capital Preservation", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Capital leakage history", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="capital_preservation_intelligence.capital_preservation_score"),
    _entry(engine_name="Capital Intelligence", owning_system="Prometheus", mission="Capital growth", dashboard="prometheus_market_analysis", section="risk", component="metric", label="Recovery Efficiency", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Capital simulations", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="capital_growth_intelligence_engine.best_capital_path.recovery_efficiency"),
    _entry(engine_name="Risk Intelligence", owning_system="Prometheus", mission="Risk governance", dashboard="prometheus_market_analysis", section="risk", component="metric", label="Risk of Ruin", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Historical closed trades", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="risk_intelligence_engine.risk_of_ruin"),
    _entry(engine_name="Capital Intelligence", owning_system="Prometheus", mission="Capital growth", dashboard="prometheus_market_analysis", section="risk", component="metric", label="Capital Efficiency", priority="High", display_order=40, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Capital growth simulations", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="capital_growth_intelligence_engine.best_capital_path.capital_efficiency"),
    _entry(engine_name="Capital Intelligence", owning_system="Prometheus", mission="Capital growth", dashboard="prometheus_market_analysis", section="risk", component="metric", label="Compounding Score", priority="Medium", display_order=50, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Capital growth simulations", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="capital_growth_intelligence_engine.best_capital_path.compounding_efficiency"),
    _entry(engine_name="Institutional Runtime Risk", owning_system="Prometheus", mission="Live risk governance", dashboard="prometheus_market_analysis", section="risk", component="metric", label="Runtime Risk State", priority="High", display_order=55, visibility="Enabled", version_introduced="v2.4", evidence_requirement="Live runtime telemetry", confidence_requirement="Operational confidence", status="Active", backward_compatibility=True, source="institutional_risk_performance_runtime", value_path="runtime_risk_governance.risk_state"),
    _entry(engine_name="Institutional Runtime Performance", owning_system="Prometheus", mission="Live risk governance", dashboard="prometheus_market_analysis", section="risk", component="metric", label="Poll p95 (ms)", priority="High", display_order=56, visibility="Enabled", version_introduced="v2.4", evidence_requirement="Runtime telemetry", confidence_requirement="Operational confidence", status="Active", backward_compatibility=True, source="institutional_risk_performance_runtime", value_path="runtime_performance.poll_duration_p95_ms"),
    _entry(engine_name="Institutional Runtime Confidence", owning_system="Prometheus", mission="Live risk governance", dashboard="prometheus_market_analysis", section="risk", component="metric", label="Runtime Confidence", priority="High", display_order=57, visibility="Enabled", version_introduced="v2.4", evidence_requirement="Runtime confidence intervals", confidence_requirement="Operational confidence", status="Active", backward_compatibility=True, source="institutional_risk_performance_runtime", value_path="runtime_statistics_confidence.sample_confidence_level"),
    _entry(engine_name="Institutional Policy Advisory", owning_system="Prometheus", mission="Live risk governance", dashboard="prometheus_market_analysis", section="risk", component="metric", label="Policy Advisory", priority="Medium", display_order=58, visibility="Enabled", version_introduced="v2.4", evidence_requirement="Runtime policy advisory", confidence_requirement="Operational confidence", status="Active", backward_compatibility=True, source="institutional_risk_performance_runtime", value_path="policy_advisory.recommendation"),
    _entry(engine_name="Institutional Policy Advisory", owning_system="Prometheus", mission="Live risk governance", dashboard="prometheus_market_analysis", section="risk", component="metric", label="Policy Gate Enabled", priority="Medium", display_order=59, visibility="Enabled", version_introduced="v2.4", evidence_requirement="Runtime policy advisory", confidence_requirement="Operational confidence", status="Active", backward_compatibility=True, source="institutional_risk_performance_runtime", value_path="policy_advisory.enforcement_active"),

    _entry(engine_name="Learning Velocity Intelligence", owning_system="Prometheus", mission="Institutional learning", dashboard="prometheus_market_analysis", section="research", component="metric", label="Learning Velocity", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Learning timeline", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="continuous_improvement_metrics.learning_velocity"),
    _entry(engine_name="Learning Intelligence", owning_system="Prometheus", mission="Institutional learning", dashboard="prometheus_market_analysis", section="research", component="metric", label="Knowledge Growth", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Historical sample growth", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="continuous_improvement_metrics.knowledge_growth"),
    _entry(engine_name="Recommendation Intelligence", owning_system="Prometheus", mission="Recommendation governance", dashboard="prometheus_market_analysis", section="research", component="metric", label="Recommendation Accuracy", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Recommendation outcomes", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="continuous_improvement_metrics.recommendation_accuracy_growth"),
    _entry(engine_name="Decision Attribution Intelligence", owning_system="Prometheus", mission="Decision quality", dashboard="prometheus_market_analysis", section="research", component="metric", label="Decision Attribution", priority="High", display_order=40, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Execution outcome attribution", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="decision_attribution_intelligence.decision_attribution_matrix", aggregation="len"),
    _entry(engine_name="Learning Intelligence", owning_system="Prometheus", mission="Institutional learning", dashboard="prometheus_market_analysis", section="research", component="metric", label="Institutional Learning Index", priority="High", display_order=50, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Learning metrics", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="continuous_improvement_metrics.institutional_learning_index"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Institutional validation", dashboard="prometheus_market_analysis", section="research", component="metric", label="Validation Reports", priority="High", display_order=52, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Zeus validation status", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="summary.total"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Institutional validation", dashboard="prometheus_market_analysis", section="research", component="metric", label="Validation Stage", priority="High", display_order=53, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Lifecycle status", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="lifecycle.current_stage"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Institutional validation", dashboard="prometheus_market_analysis", section="research", component="metric", label="Research Status", priority="High", display_order=54, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Candidate pipelines", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="research_status"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Institutional validation", dashboard="prometheus_market_analysis", section="research", component="metric", label="Institutional Maturity", priority="High", display_order=55, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Historical validation sample", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="institutional_maturity"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Institutional validation", dashboard="prometheus_market_analysis", section="research", component="metric", label="Validation Learning Velocity", priority="Medium", display_order=56, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Validation intake velocity", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="learning_velocity"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Institutional validation", dashboard="prometheus_market_analysis", section="research", component="metric", label="Validated by Zeus", priority="Medium", display_order=57, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Validation engine origin", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="validation_engine", aggregation="validated_by_zeus"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Institutional validation", dashboard="prometheus_market_analysis", section="research", component="metric", label="Validation Confidence", priority="Medium", display_order=58, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Institutional confidence", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="summary.institutional_confidence"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Institutional validation", dashboard="prometheus_market_analysis", section="research", component="metric", label="Validation Date", priority="Medium", display_order=59, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Validation timestamp", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="generated_at"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Institutional validation", dashboard="prometheus_market_analysis", section="research", component="metric", label="Validation Version", priority="Medium", display_order=60, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Validation version", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="version"),

    _entry(engine_name="Edge Intelligence", owning_system="Prometheus", mission="Edge preservation", dashboard="prometheus_market_analysis", section="edge", component="metric", label="Edge Robustness", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Rolling edge metrics", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_edge_learning_engine.edge_robustness"),
    _entry(engine_name="Edge Intelligence", owning_system="Prometheus", mission="Edge preservation", dashboard="prometheus_market_analysis", section="edge", component="metric", label="Edge Concentration", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Context distribution", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_edge_learning_engine.edge_concentration"),
    _entry(engine_name="Edge Intelligence", owning_system="Prometheus", mission="Edge preservation", dashboard="prometheus_market_analysis", section="edge", component="metric", label="Edge Breadth", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Context distribution", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_edge_learning_engine.edge_breadth"),
    _entry(engine_name="Edge Intelligence", owning_system="Prometheus", mission="Edge preservation", dashboard="prometheus_market_analysis", section="edge", component="metric", label="Rolling Expectancy", priority="High", display_order=40, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Closed trade history", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_edge_learning_engine.expectancy"),
    _entry(engine_name="Edge Intelligence", owning_system="Prometheus", mission="Edge preservation", dashboard="prometheus_market_analysis", section="edge", component="metric", label="Rolling Sharpe", priority="High", display_order=50, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Rolling return history", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_edge_learning_engine.rolling_sharpe"),
    _entry(engine_name="Edge Intelligence", owning_system="Prometheus", mission="Edge preservation", dashboard="prometheus_market_analysis", section="edge", component="metric", label="Rolling Sortino", priority="High", display_order=60, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Rolling return history", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_edge_learning_engine.rolling_sortino"),
    _entry(engine_name="Recommendation Intelligence", owning_system="Prometheus", mission="Recommendation governance", dashboard="prometheus_market_analysis", section="research", component="text", label="Research Recommendation Summary", priority="Medium", display_order=60, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Recommendations", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="recommendation_engine_evolution.recommendations", aggregation="top_recommendations_summary"),

    # Prometheus Execution Academy
    _entry(engine_name="Execution Location Intelligence", owning_system="Prometheus", mission="Execution evaluation", dashboard="prometheus_execution_academy", section="execution_intelligence", component="metric", label="Execution Location Grade", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Execution location research", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_location_intelligence.execution_location_quality"),
    _entry(engine_name="Execution Intelligence", owning_system="Prometheus", mission="Execution evaluation", dashboard="prometheus_execution_academy", section="execution_intelligence", component="metric", label="Execution Efficiency", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Execution telemetry", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_location_intelligence.execution_efficiency"),
    _entry(engine_name="Structural Price Location Intelligence", owning_system="Prometheus", mission="Execution evaluation", dashboard="prometheus_execution_academy", section="execution_intelligence", component="metric", label="Structural Entry Score", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Structure context evidence", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_location_intelligence.structural_position"),
    _entry(engine_name="Liquidity Intelligence", owning_system="Prometheus", mission="Execution evaluation", dashboard="prometheus_execution_academy", section="execution_intelligence", component="metric", label="Liquidity Avoidance", priority="High", display_order=40, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Liquidity sweep observations", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_location_intelligence.sweep_exposure", aggregation="invert_fraction"),
    _entry(engine_name="Capital Preservation Intelligence", owning_system="Prometheus", mission="Execution evaluation", dashboard="prometheus_execution_academy", section="execution_intelligence", component="metric", label="Capital Leakage", priority="High", display_order=50, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Capital leakage research", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="capital_preservation_intelligence.total_capital_leakage"),

    _entry(engine_name="Capital Intelligence", owning_system="Prometheus", mission="Capital evaluation", dashboard="prometheus_execution_academy", section="capital_intelligence", component="metric", label="Capital Efficiency", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Capital simulations", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="capital_growth_intelligence_engine.best_capital_path.capital_efficiency"),
    _entry(engine_name="Capital Intelligence", owning_system="Prometheus", mission="Capital evaluation", dashboard="prometheus_execution_academy", section="capital_intelligence", component="metric", label="Recovery Efficiency", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Capital simulations", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="capital_growth_intelligence_engine.best_capital_path.recovery_efficiency"),
    _entry(engine_name="Capital Intelligence", owning_system="Prometheus", mission="Capital evaluation", dashboard="prometheus_execution_academy", section="capital_intelligence", component="metric", label="Compounding Score", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Capital simulations", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="capital_growth_intelligence_engine.best_capital_path.compounding_efficiency"),
    _entry(engine_name="Risk Intelligence", owning_system="Prometheus", mission="Capital evaluation", dashboard="prometheus_execution_academy", section="capital_intelligence", component="metric", label="Risk of Ruin", priority="High", display_order=40, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Closed trade history", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="risk_intelligence_engine.risk_of_ruin"),
    _entry(engine_name="Capital Intelligence", owning_system="Prometheus", mission="Capital evaluation", dashboard="prometheus_execution_academy", section="capital_intelligence", component="metric", label="Growth Stability", priority="High", display_order=50, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Capital simulations", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="capital_growth_intelligence_engine.best_capital_path.growth_stability"),
    _entry(engine_name="Institutional Runtime Risk", owning_system="Prometheus", mission="Execution safety", dashboard="prometheus_execution_academy", section="capital_intelligence", component="metric", label="Runtime Risk State", priority="High", display_order=56, visibility="Enabled", version_introduced="v2.4", evidence_requirement="Live runtime telemetry", confidence_requirement="Operational confidence", status="Active", backward_compatibility=True, source="institutional_risk_performance_runtime", value_path="runtime_risk_governance.risk_state"),
    _entry(engine_name="Institutional Runtime Confidence", owning_system="Prometheus", mission="Execution safety", dashboard="prometheus_execution_academy", section="capital_intelligence", component="metric", label="Confidence CI95", priority="Medium", display_order=57, visibility="Enabled", version_introduced="v2.4", evidence_requirement="Confidence interval telemetry", confidence_requirement="Operational confidence", status="Active", backward_compatibility=True, source="institutional_risk_performance_runtime", value_path="runtime_statistics_confidence.poll_duration_ci95_label"),
    _entry(engine_name="Institutional Policy Advisory", owning_system="Prometheus", mission="Execution safety", dashboard="prometheus_execution_academy", section="capital_intelligence", component="metric", label="Policy Advisory", priority="Medium", display_order=58, visibility="Enabled", version_introduced="v2.4", evidence_requirement="Runtime policy advisory", confidence_requirement="Operational confidence", status="Active", backward_compatibility=True, source="institutional_risk_performance_runtime", value_path="policy_advisory.recommendation"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Feature validation", dashboard="prometheus_execution_academy", section="capital_intelligence", component="metric", label="Feature Validation Reports", priority="Medium", display_order=55, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Feature leakage validation", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="summary.by_domain.feature"),

    _entry(engine_name="Learning Velocity Intelligence", owning_system="Prometheus", mission="Learning evaluation", dashboard="prometheus_execution_academy", section="learning_intelligence", component="metric", label="Learning Velocity", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Learning timeline", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="continuous_improvement_metrics.learning_velocity"),
    _entry(engine_name="Learning Intelligence", owning_system="Prometheus", mission="Learning evaluation", dashboard="prometheus_execution_academy", section="learning_intelligence", component="metric", label="Knowledge Growth", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Sample growth", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="continuous_improvement_metrics.knowledge_growth"),
    _entry(engine_name="Learning Intelligence", owning_system="Prometheus", mission="Learning evaluation", dashboard="prometheus_execution_academy", section="learning_intelligence", component="metric", label="Institutional Learning Index", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Learning metrics", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="continuous_improvement_metrics.institutional_learning_index"),
    _entry(engine_name="Learning Intelligence", owning_system="Prometheus", mission="Learning evaluation", dashboard="prometheus_execution_academy", section="learning_intelligence", component="metric", label="Hypothesis Success", priority="Medium", display_order=40, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Hypothesis generation", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="historical_knowledge_mining.active_hypotheses", aggregation="len"),
    _entry(engine_name="Research Intelligence", owning_system="Prometheus", mission="Learning evaluation", dashboard="prometheus_execution_academy", section="learning_intelligence", component="metric", label="Research Confidence", priority="Medium", display_order=50, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Research library", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="continuous_improvement_metrics.research_confidence"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Validation evaluation", dashboard="prometheus_execution_academy", section="learning_intelligence", component="metric", label="Validation Progress", priority="High", display_order=55, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Validation lifecycle", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="summary.total"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Validation evaluation", dashboard="prometheus_execution_academy", section="learning_intelligence", component="metric", label="Validation Lifecycle", priority="High", display_order=56, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Validation lifecycle", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="lifecycle.current_stage"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Validation evaluation", dashboard="prometheus_execution_academy", section="learning_intelligence", component="metric", label="Validation Confidence", priority="Medium", display_order=57, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Institutional confidence", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="summary.institutional_confidence"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Validation evaluation", dashboard="prometheus_execution_academy", section="learning_intelligence", component="metric", label="Institutional Approval", priority="Medium", display_order=58, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Approval counts", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="queue.counts.Approved"),

    _entry(engine_name="Recommendation Intelligence", owning_system="Prometheus", mission="Recommendation evaluation", dashboard="prometheus_execution_academy", section="recommendation_intelligence", component="metric", label="Recommendation Accuracy", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Recommendation feedback", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="continuous_improvement_metrics.recommendation_accuracy_growth"),
    _entry(engine_name="Recommendation Intelligence", owning_system="Prometheus", mission="Recommendation evaluation", dashboard="prometheus_execution_academy", section="recommendation_intelligence", component="metric", label="Recommendation Confidence", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Recommendation outputs", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="recommendation_engine_evolution.recommendations", aggregation="mean_confidence"),
    _entry(engine_name="Recommendation Intelligence", owning_system="Prometheus", mission="Recommendation evaluation", dashboard="prometheus_execution_academy", section="recommendation_intelligence", component="metric", label="Recommendation Success", priority="Medium", display_order=30, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Recommendation outcomes", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="recommendation_engine_evolution.feedback_loop.outcome_tracking", aggregation="len"),
    _entry(engine_name="Recommendation Intelligence", owning_system="Prometheus", mission="Recommendation evaluation", dashboard="prometheus_execution_academy", section="recommendation_intelligence", component="metric", label="Recommendation Adoption", priority="Medium", display_order=40, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Recommendation outcomes", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="recommendation_engine_evolution.feedback_loop.outcome_tracking", aggregation="count_implemented"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Recommendation validation", dashboard="prometheus_execution_academy", section="recommendation_intelligence", component="metric", label="Recommendation Validation Reports", priority="Medium", display_order=45, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Recommendation validation", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="summary.by_domain.recommendation"),

    _entry(engine_name="Edge Intelligence", owning_system="Prometheus", mission="Edge evaluation", dashboard="prometheus_execution_academy", section="edge_intelligence", component="metric", label="Edge Stability", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Rolling edge metrics", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_edge_learning_engine.edge_stability"),
    _entry(engine_name="Edge Intelligence", owning_system="Prometheus", mission="Edge evaluation", dashboard="prometheus_execution_academy", section="edge_intelligence", component="metric", label="Edge Robustness", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Rolling edge metrics", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_edge_learning_engine.edge_robustness"),
    _entry(engine_name="Edge Intelligence", owning_system="Prometheus", mission="Edge evaluation", dashboard="prometheus_execution_academy", section="edge_intelligence", component="metric", label="Edge Durability", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Rolling edge metrics", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_edge_learning_engine.edge_durability"),
    _entry(engine_name="Edge Intelligence", owning_system="Prometheus", mission="Edge evaluation", dashboard="prometheus_execution_academy", section="edge_intelligence", component="metric", label="Edge Confidence", priority="High", display_order=40, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Rolling edge metrics", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="execution_edge_learning_engine.edge_confidence"),
    _entry(engine_name="Edge Intelligence", owning_system="Prometheus", mission="Edge evaluation", dashboard="prometheus_execution_academy", section="edge_intelligence", component="metric", label="Edge Evolution", priority="Medium", display_order=50, visibility="Enabled", version_introduced="v2.1", evidence_requirement="Edge evolution history", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="research_library_evolution.edge_evolution_history", aggregation="len"),

    _entry(engine_name="Decision Attribution Intelligence", owning_system="Prometheus", mission="Decision evaluation", dashboard="prometheus_execution_academy", section="decision_attribution", component="table", label="Decision Attribution", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.2", evidence_requirement="Execution attribution history", confidence_requirement="Research confidence", status="Active", backward_compatibility=True, source="prometheus_evolution", value_path="decision_attribution_intelligence.decision_attribution_matrix", table_columns=("factor", "success_contribution", "failure_contribution", "net_institutional_edge")),

    # Hermes dashboard
    _entry(engine_name="Learning Velocity Intelligence", owning_system="Hermes", mission="Pattern learning", dashboard="hermes_dashboard", section="learning_intelligence", component="metric", label="Learning Velocity", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Learning timeline", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="timeline.learning_velocity"),
    _entry(engine_name="Learning Intelligence", owning_system="Hermes", mission="Pattern learning", dashboard="hermes_dashboard", section="learning_intelligence", component="metric", label="Knowledge Growth", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Research library growth", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.research_library", aggregation="len"),
    _entry(engine_name="Pattern Context Intelligence", owning_system="Hermes", mission="Pattern learning", dashboard="hermes_dashboard", section="learning_intelligence", component="metric", label="Research Confidence", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Context evidence", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.academy_subject.knowledge_confidence"),
    _entry(engine_name="Pattern Lifecycle Intelligence", owning_system="Hermes", mission="Pattern learning", dashboard="hermes_dashboard", section="learning_intelligence", component="metric", label="Mastery", priority="Medium", display_order=40, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Academy evidence", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.academy_subject.mastery"),
    _entry(engine_name="Pattern Lifecycle Intelligence", owning_system="Hermes", mission="Pattern learning", dashboard="hermes_dashboard", section="learning_intelligence", component="metric", label="Maturity", priority="Medium", display_order=50, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Academy evidence", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.academy_subject.current_grade"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Pattern validation", dashboard="hermes_dashboard", section="learning_intelligence", component="metric", label="Pattern Validation Status", priority="High", display_order=55, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Pattern candidate validation", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="summary.by_domain.pattern"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Pattern validation", dashboard="hermes_dashboard", section="learning_intelligence", component="metric", label="Validation Confidence", priority="Medium", display_order=56, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Institutional confidence", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="summary.institutional_confidence"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Pattern validation", dashboard="hermes_dashboard", section="learning_intelligence", component="metric", label="Validation History", priority="Medium", display_order=57, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Historical validation records", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="evidence_library.historical_validation_records"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Pattern validation", dashboard="hermes_dashboard", section="learning_intelligence", component="metric", label="Validation Version", priority="Medium", display_order=58, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Validation version", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="version"),
    _entry(engine_name="Zeus Validation", owning_system="Zeus", mission="Pattern validation", dashboard="hermes_dashboard", section="learning_intelligence", component="metric", label="Pattern Approval Status", priority="Medium", display_order=59, visibility="Enabled", version_introduced="v2.3", evidence_requirement="Approval counts", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation", value_path="queue.counts.Approved"),

    _entry(engine_name="Pattern Context Intelligence", owning_system="Hermes", mission="Pattern intelligence", dashboard="hermes_dashboard", section="pattern_intelligence", component="metric", label="Context Profiles", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Pattern context profiles", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.context_profiles", aggregation="len"),
    _entry(engine_name="Pattern Context Intelligence", owning_system="Hermes", mission="Pattern intelligence", dashboard="hermes_dashboard", section="pattern_intelligence", component="metric", label="Pattern Context Library", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Pattern context library", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.pattern_context_library", aggregation="len"),
    _entry(engine_name="Pattern Edge Intelligence", owning_system="Hermes", mission="Pattern intelligence", dashboard="hermes_dashboard", section="pattern_intelligence", component="metric", label="Pattern Edge Intelligence", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Pattern edge history", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="edge_stability.pattern_intelligence_edge"),
    _entry(engine_name="Pattern Lifecycle Intelligence", owning_system="Hermes", mission="Pattern intelligence", dashboard="hermes_dashboard", section="pattern_intelligence", component="metric", label="Pattern Lifecycle Intelligence", priority="Medium", display_order=40, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Lifecycle counts", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="pattern_intelligence.lifecycle_counts", aggregation="sum_values"),
    _entry(engine_name="Pattern Context Intelligence", owning_system="Hermes", mission="Pattern intelligence", dashboard="hermes_dashboard", section="pattern_intelligence", component="table", label="Pattern Context Profiles", priority="Medium", display_order=50, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Pattern context profiles", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.context_profiles", table_columns=("pattern_id", "structural_price_location", "liquidity_context", "premium_discount", "market_structure", "volatility_phase", "session_context", "knowledge_confidence")),

    _entry(engine_name="Pattern Edge Intelligence", owning_system="Hermes", mission="Pattern intelligence", dashboard="hermes_dashboard", section="edge_intelligence", component="metric", label="Edge Evolution", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Edge history", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="edge_stability.history", aggregation="len"),
    _entry(engine_name="Context Evolution Intelligence", owning_system="Hermes", mission="Pattern intelligence", dashboard="hermes_dashboard", section="edge_intelligence", component="metric", label="Context Evolution", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Pattern context library", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.pattern_context_library", aggregation="len"),
    _entry(engine_name="Learning Velocity Intelligence", owning_system="Hermes", mission="Pattern intelligence", dashboard="hermes_dashboard", section="edge_intelligence", component="metric", label="Pattern Confidence Growth", priority="Medium", display_order=30, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Confidence analytics", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="confidence_intelligence.confidence_stability"),
    _entry(engine_name="Pattern Context Intelligence", owning_system="Hermes", mission="Pattern intelligence", dashboard="hermes_dashboard", section="edge_intelligence", component="metric", label="Research Evidence", priority="Medium", display_order=40, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Research library", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.research_library", aggregation="len"),

    _entry(engine_name="Trade Lifecycle Intelligence", owning_system="Hermes", mission="Lifecycle execution intelligence", dashboard="hermes_dashboard", section="tli_intelligence", component="metric", label="Lifecycle Expectancy", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.5", evidence_requirement="Closed lifecycle trades", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="trade_lifecycle_intelligence.summary.expectancy"),
    _entry(engine_name="Trade Lifecycle Intelligence", owning_system="Hermes", mission="Lifecycle execution intelligence", dashboard="hermes_dashboard", section="tli_intelligence", component="metric", label="Reward Efficiency", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.5", evidence_requirement="Reward capture history", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="trade_lifecycle_intelligence.summary.reward_efficiency"),
    _entry(engine_name="Trade Lifecycle Intelligence", owning_system="Hermes", mission="Lifecycle execution intelligence", dashboard="hermes_dashboard", section="tli_intelligence", component="metric", label="Lifecycle Efficiency", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.5", evidence_requirement="Lifecycle telemetry", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="trade_lifecycle_intelligence.summary.lifecycle_efficiency"),
    _entry(engine_name="Trade Lifecycle Intelligence", owning_system="Hermes", mission="Lifecycle execution intelligence", dashboard="hermes_dashboard", section="tli_intelligence", component="metric", label="State Observability", priority="High", display_order=40, visibility="Enabled", version_introduced="v2.5", evidence_requirement="State transition history", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="trade_lifecycle_intelligence.summary.state_observability_score"),
    _entry(engine_name="Trade Lifecycle Intelligence", owning_system="Hermes", mission="Lifecycle execution intelligence", dashboard="hermes_dashboard", section="tli_intelligence", component="metric", label="Average Hold (sec)", priority="Medium", display_order=50, visibility="Enabled", version_introduced="v2.5", evidence_requirement="Duration telemetry", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="trade_lifecycle_intelligence.summary.average_hold_time_sec"),
    _entry(engine_name="Trade Lifecycle Intelligence", owning_system="Hermes", mission="Lifecycle execution intelligence", dashboard="hermes_dashboard", section="tli_intelligence", component="table", label="Top Lifecycle Patterns", priority="Medium", display_order=60, visibility="Enabled", version_introduced="v2.5", evidence_requirement="Lifecycle sequence clusters", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="trade_lifecycle_intelligence.modules.pattern_lifecycle_intelligence.top_expectancy_patterns", table_columns=("pattern", "samples", "best_sequence", "expectancy", "capture_ratio", "sequence_diversity")),

    _entry(engine_name="IDIP", owning_system="Hermes", mission="Institutional decision intelligence", dashboard="hermes_dashboard", section="idip_intelligence", component="metric", label="IDIP Expectancy", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.6", evidence_requirement="IDIP decision history", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="idip_summary.expectancy"),
    _entry(engine_name="IDIP", owning_system="Hermes", mission="Institutional decision intelligence", dashboard="hermes_dashboard", section="idip_intelligence", component="metric", label="IDIP Reward Efficiency", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.6", evidence_requirement="IDIP reward capture evidence", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="idip_summary.reward_efficiency"),
    _entry(engine_name="IDIP", owning_system="Hermes", mission="Institutional decision intelligence", dashboard="hermes_dashboard", section="idip_intelligence", component="metric", label="IDIP Decision Quality", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.6", evidence_requirement="IDIP decision attribution evidence", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="idip_summary.decision_quality"),
    _entry(engine_name="IDIP", owning_system="Hermes", mission="Institutional decision intelligence", dashboard="hermes_dashboard", section="idip_intelligence", component="metric", label="IDIP Unknown Exits", priority="Medium", display_order=40, visibility="Enabled", version_introduced="v2.6", evidence_requirement="IDIP exit classification evidence", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="idip_summary.unknown_exit_count"),
    _entry(engine_name="IDIP", owning_system="Hermes", mission="Institutional decision intelligence", dashboard="hermes_dashboard", section="idip_intelligence", component="metric", label="IDIP Maturity", priority="Medium", display_order=50, visibility="Enabled", version_introduced="v2.6", evidence_requirement="IDIP sample growth", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="idip_summary.maturity"),
    _entry(engine_name="IDIP", owning_system="Hermes", mission="Institutional decision intelligence", dashboard="hermes_dashboard", section="idip_intelligence", component="table", label="IDIP Portfolio Exposure", priority="Medium", display_order=60, visibility="Enabled", version_introduced="v2.6", evidence_requirement="Portfolio contribution evidence", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_status", value_path="idip.engines.portfolio_intelligence.pattern_concentration", table_columns=("pattern", "samples", "share_pct", "return_contribution", "expectancy")),

    # Knowledge growth dashboard: institutional dataset architecture and validation board separation
    _entry(engine_name="Institutional Dataset Architecture", owning_system="Olympus", mission="Institutional dataset quality", dashboard="knowledge_growth", section="dataset_quality", component="metric", label="Dataset Quality Score", priority="High", display_order=10, visibility="Enabled", version_introduced="idav-v1.0", evidence_requirement="Institutional dataset rows", confidence_requirement="Zeus-governed evidence", status="Active", backward_compatibility=True, source="institutional_dataset_architecture", value_path="dataset_quality.dataset_quality_score"),
    _entry(engine_name="Institutional Dataset Architecture", owning_system="Olympus", mission="Institutional dataset quality", dashboard="knowledge_growth", section="dataset_quality", component="metric", label="Completeness", priority="High", display_order=20, visibility="Enabled", version_introduced="idav-v1.0", evidence_requirement="Required field coverage", confidence_requirement="Zeus-governed evidence", status="Active", backward_compatibility=True, source="institutional_dataset_architecture", value_path="dataset_quality.metrics.completeness"),
    _entry(engine_name="Institutional Dataset Architecture", owning_system="Olympus", mission="Institutional dataset quality", dashboard="knowledge_growth", section="dataset_quality", component="metric", label="Coverage", priority="High", display_order=30, visibility="Enabled", version_introduced="idav-v1.0", evidence_requirement="Session/regime/day coverage", confidence_requirement="Zeus-governed evidence", status="Active", backward_compatibility=True, source="institutional_dataset_architecture", value_path="dataset_quality.metrics.coverage"),
    _entry(engine_name="Institutional Dataset Architecture", owning_system="Olympus", mission="Institutional dataset quality", dashboard="knowledge_growth", section="dataset_quality", component="metric", label="Validation Coverage", priority="High", display_order=40, visibility="Enabled", version_introduced="idav-v1.0", evidence_requirement="Zeus validation linkages", confidence_requirement="Zeus-governed evidence", status="Active", backward_compatibility=True, source="institutional_dataset_architecture", value_path="dataset_quality.metrics.validation_coverage"),
    _entry(engine_name="Zeus Pattern Validation Board", owning_system="Zeus", mission="Independent pattern governance", dashboard="knowledge_growth", section="zeus_boards", component="metric", label="Pattern Board Reports", priority="High", display_order=10, visibility="Enabled", version_introduced="idav-v1.0", evidence_requirement="Pattern board ledger", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation_boards", value_path="zeus_validation_boards.pattern_validation_board.total_reports"),
    _entry(engine_name="Zeus Pattern Validation Board", owning_system="Zeus", mission="Independent pattern governance", dashboard="knowledge_growth", section="zeus_boards", component="metric", label="Pattern Board Pass Rate", priority="High", display_order=20, visibility="Enabled", version_introduced="idav-v1.0", evidence_requirement="Pattern board outcomes", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation_boards", value_path="zeus_validation_boards.pattern_validation_board.pass_rate"),
    _entry(engine_name="Zeus Strategy Validation Board", owning_system="Zeus", mission="Independent strategy governance", dashboard="knowledge_growth", section="zeus_boards", component="metric", label="Strategy Board Reports", priority="High", display_order=30, visibility="Enabled", version_introduced="idav-v1.0", evidence_requirement="Strategy board ledger", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation_boards", value_path="zeus_validation_boards.strategy_validation_board.total_reports"),
    _entry(engine_name="Zeus Strategy Validation Board", owning_system="Zeus", mission="Independent strategy governance", dashboard="knowledge_growth", section="zeus_boards", component="metric", label="Strategy Board Pass Rate", priority="High", display_order=40, visibility="Enabled", version_introduced="idav-v1.0", evidence_requirement="Strategy board outcomes", confidence_requirement="Validation evidence", status="Active", backward_compatibility=True, source="zeus_validation_boards", value_path="zeus_validation_boards.strategy_validation_board.pass_rate"),

    # Hermes pattern context dashboard
    _entry(engine_name="Pattern Context Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="context_summary", component="metric", label="Pattern Profiles", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Context profiles", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.context_profiles", aggregation="len"),
    _entry(engine_name="Pattern Context Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="context_summary", component="metric", label="Research Observations", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Research library", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.research_library", aggregation="len"),
    _entry(engine_name="Session Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="context_summary", component="metric", label="Best Session", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Context profiles", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.best_session"),
    _entry(engine_name="Market Regime Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="context_summary", component="metric", label="Best Regime", priority="High", display_order=40, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Context profiles", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.best_market_regime"),
    _entry(engine_name="Pattern Context Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="context_summary", component="metric", label="Best Hour", priority="Medium", display_order=50, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Context profiles", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.best_hour"),
    _entry(engine_name="Pattern Context Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="context_summary", component="metric", label="Best Day", priority="Medium", display_order=60, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Context profiles", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.best_day"),
    _entry(engine_name="Learning Velocity Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="learning_summary", component="metric", label="Learning Velocity", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Learning timeline", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="metrics.learning_velocity"),
    _entry(engine_name="Learning Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="learning_summary", component="metric", label="Knowledge Growth", priority="High", display_order=20, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Research library", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.research_library", aggregation="len"),
    _entry(engine_name="Pattern Edge Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="learning_summary", component="metric", label="Pattern Stability", priority="High", display_order=30, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Pattern library", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="metrics.pattern_stability"),
    _entry(engine_name="Learning Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="learning_summary", component="metric", label="Pattern Confidence Growth", priority="Medium", display_order=40, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Academy subject", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.academy_subject.knowledge_confidence"),
    _entry(engine_name="Research Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="learning_summary", component="metric", label="Research Confidence", priority="Medium", display_order=50, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Academy subject", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.academy_subject.knowledge_confidence"),
    _entry(engine_name="Pattern Lifecycle Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="learning_summary", component="metric", label="Mastery Growth", priority="Medium", display_order=60, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Academy subject", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.academy_subject.mastery"),
    _entry(engine_name="Pattern Context Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="pattern_context_profiles", component="table", label="Pattern Context Profiles", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Context profiles", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.context_profiles", table_columns=("pattern_id", "structural_price_location", "liquidity_context", "premium_discount", "retracement_behaviour", "market_structure", "volatility_phase", "session_context", "expectancy", "knowledge_confidence")),
    _entry(engine_name="Pattern Evolution Intelligence", owning_system="Hermes", mission="Pattern context", dashboard="hermes_pattern_context", section="pattern_context_library", component="table", label="Expanded Pattern Context Library", priority="High", display_order=10, visibility="Enabled", version_introduced="v2.0", evidence_requirement="Pattern context library", confidence_requirement="Knowledge confidence", status="Active", backward_compatibility=True, source="hermes_analytics", value_path="pattern_context_intelligence.pattern_context_library", table_columns=("pattern_id", "occurrences", "win_rate", "expectancy", "best_session", "best_market_regime", "pattern_evolution_history", "context_evolution", "structural_behaviour", "liquidity_behaviour", "edge_evolution", "pattern_maturity", "knowledge_confidence")),
)


def dashboard_registry_entries() -> list[dict[str, Any]]:
    return [entry.as_dict() for entry in sorted(_REGISTRY, key=lambda item: (item.dashboard, item.section, item.display_order))]


def _get_path(data: Any, path: str) -> Any:
    if not path:
        return data
    current = data
    for part in path.split("."):
        if isinstance(current, dict):
            current = current.get(part)
        else:
            return None
    return current


def _resolve_aggregation(value: Any, aggregation: str, default_value: Any) -> Any:
    if value is None:
        return default_value
    if aggregation == "direct":
        return value
    if aggregation == "len":
        return len(value) if isinstance(value, (list, tuple, dict, set)) else default_value
    if aggregation == "mean_confidence":
        if not isinstance(value, list) or not value:
            return default_value
        vals = []
        for row in value:
            try:
                vals.append(float((row or {}).get("confidence", 0.0) or 0.0))
            except Exception:
                continue
        return round(sum(vals) / len(vals), 2) if vals else default_value
    if aggregation == "count_implemented":
        if not isinstance(value, list):
            return default_value
        return sum(1 for row in value if isinstance(row, dict) and row.get("implemented"))
    if aggregation == "invert_fraction":
        try:
            return round(1.0 - float(value), 4)
        except Exception:
            return default_value
    if aggregation == "sum_values":
        if isinstance(value, dict):
            try:
                return sum(int(v or 0) for v in value.values())
            except Exception:
                return default_value
        return default_value
    if aggregation == "maturity_from_sample":
        try:
            sample = int(value or 0)
        except Exception:
            return default_value
        if sample >= 300:
            return "Institutional"
        if sample >= 120:
            return "Advanced"
        if sample >= 50:
            return "Developing"
        return "Emerging"
    if aggregation == "top_recommendations_summary":
        if not isinstance(value, list) or not value:
            return default_value
        parts = []
        for row in value[:3]:
            parts.append(f"{row.get('recommendation_priority', 'Low')}: {str(row.get('finding', 'Awaiting Historical Data')).strip()[:80]}")
        return " | ".join(parts) if parts else default_value
    if aggregation == "validated_by_zeus":
        return "Yes" if str(value or "").lower() == "zeus" else default_value
    return value


def resolve_dashboard_section(dashboard: str, section: str, sources: dict[str, Any]) -> list[dict[str, Any]]:
    resolved: list[dict[str, Any]] = []
    for entry in sorted((item for item in _REGISTRY if item.dashboard == dashboard and item.section == section and item.visibility.lower() == "enabled"), key=lambda item: item.display_order):
        source_payload = sources.get(entry.source, {})
        raw_value = _get_path(source_payload, entry.value_path)
        value = _resolve_aggregation(raw_value, entry.aggregation, entry.default_value)
        delta_value = _get_path(source_payload, entry.delta_path) if entry.delta_path else None
        resolved.append({**entry.as_dict(), "resolved_value": value, "resolved_delta": delta_value})
    return resolved


def dashboard_registry_snapshot() -> dict[str, Any]:
    return {
        "registry_version": _CONTRACT_VERSION,
        "entries": dashboard_registry_entries(),
    }